# Generated by Django 4.2.3 on 2023-07-26 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sup', '0002_alter_rentalslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalslot',
            name='selected_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sup.rentalslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
